name: MyWorkflow

on:
  
  workflow_dispatch:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  Greeting: Bye
  file_name: "python.py"
  # num: 10.5
  # message: ${{ secrets.SECRET_TOKEN }}
  # pyhton main.py // python $file_name
  
  
jobs:
  
  print_Message_on_ubuntu:
  
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo $message
          echo test, and deploy your project.
       