name: TestWorkflows1

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  file_name: python.py
  
  jobs:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v3

     
      - name: Run a pyhton file
        run: echo hi iam running within github with ubuntu!

      
     
       